listener 1883
allow_anonymous true

# Persistence
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# When we integrate with EMQX Cloud, we will configure
# the MQTT Bridge settings here. For now, it just accepts
# connections from the Portentas on the LAN.
