; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7
framework = arduino
build_flags = 
	-Iinclude/air_sensor
	-Iinclude/soil_sensor
	-Iinclude/modbus_controller
lib_deps = 
	Ethernet
	arduino-libraries/ArduinoModbus@^1.0.9
	arduino-libraries/ArduinoRS485@^1.1.1
	arduino-libraries/Arduino_PortentaMachineControl@^1.0.5
	matthijskooijman/Dsmr@^0.1
