; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
lib_deps = 
	arduino-libraries/ArduinoModbus@^1.0.9
	arduino-libraries/ArduinoRS485@^1.1.1
	arduino-libraries/Arduino_PortentaMachineControl@^1.0.5
	arduino-libraries/ArduinoMqttClient@^0.1.8
build_flags = 
	-I "${platformio.packages_dir}/framework-arduino-mbed/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include"
	-I "${platformio.packages_dir}/framework-arduino-mbed/cores/arduino/mbed/connectivity/lwipstack/include/lwipstack"
	-I "${platformio.packages_dir}/framework-arduino-mbed/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat/posix"
	-I "${platformio.packages_dir}/framework-arduino-mbed/cores/arduino/mbed/connectivity/lwipstack/lwip-sys"

[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7
build_src_filter = +<m7/> -<m4/>

[env:portenta_h7_m4]
platform = ststm32
board = portenta_h7_m4
build_src_filter = +<m4/> -<m7/>
